/**
 * Subject prefix to department name, from catalog.illinois.edu/courses-of-instruction.
 *
 * The index carries only the prefix, so a student who searched "accounting"
 * found six courses with the word in their title and none of the forty filed
 * under ACCY, whose titles say "Accountancy". The names let a search match the
 * department a student would say out loud. Generated on 2026-09-20 from the
 * catalog index page; regenerate when a prefix is added.
 */
export const ILLINOIS_SUBJECT_NAMES: Record<string, string> = {
  "AAS": "Asian American Studies",
  "ABE": "Agricultural and Biological Eng",
  "ACCY": "Accountancy",
  "ACE": "Agr & Consumer Economics",
  "ACES": "Agr, Consumer, & Env Sciences",
  "ADV": "Advertising",
  "AE": "Aerospace Engineering",
  "AFAS": "Air Force Aerospace Studies",
  "AFRO": "African American Studies",
  "AFST": "African Studies",
  "AGCM": "Agricultural Communications",
  "AGED": "Agricultural Education",
  "AHS": "Applied Health Sci Courses",
  "AIS": "American Indian Studies",
  "ALEC": "Agricultural Leadership, Education, & Communications",
  "ANSC": "Animal Sciences",
  "ANTH": "Anthropology",
  "ARAB": "Arabic",
  "ARCH": "Architecture",
  "ART": "Art",
  "ARTD": "Art--Design",
  "ARTE": "Art--Education",
  "ARTF": "Art--Foundation",
  "ARTH": "Art--History",
  "ARTJ": "Japanese Arts and Aesthetics",
  "ARTS": "Art--Studio",
  "ASRM": "Actuarial Science & Risk Management",
  "ASST": "Asian Studies",
  "ASTR": "Astronomy",
  "ATMS": "Atmospheric Sciences",
  "BADM": "Business Administration",
  "BASQ": "Basque",
  "BCOG": "Brain and Cognitive Science",
  "BCS": "Bosnian-Croatian-Serbian",
  "BDI": "Business Data & Innovation",
  "BIOC": "Biochemistry",
  "BIOE": "Bioengineering",
  "BIOL": "Biology",
  "BIOP": "Biophysics",
  "BSE": "Biomedical Sciences and Engineering",
  "BTW": "Business and Technical Writing",
  "BULG": "Bulgarian",
  "BUS": "Business",
  "CAS": "Center for Advanced Study",
  "CATL": "Catalan",
  "CB": "Comparative Biosciences",
  "CDB": "Cell and Developmental Biology",
  "CEE": "Civil and Environ Engineering",
  "CGGE": "Study of Global Gender Equity",
  "CHBE": "Chemical and Biomolecular Engineering",
  "CHEM": "Chemistry",
  "CHIN": "Chinese",
  "CHP": "Campus Honors Program",
  "CI": "Curriculum and Instruction",
  "CIC": "Committee on Inst Cooperation",
  "CLCV": "Classical Civilization",
  "CLE": "Clinical Sciences and Engineering",
  "CMN": "Communication",
  "CPSC": "Crop Sciences",
  "CS": "Computer Science",
  "CSE": "Computational Science and Engineering",
  "CW": "Creative Writing",
  "CWL": "Comparative & World Literature",
  "CZCH": "Czech",
  "DANC": "Dance",
  "DTX": "Human-Centered Design & Design Thinking",
  "EALC": "East Asian Languages & Cultures",
  "ECE": "Electrical and Computer Engineering",
  "ECON": "Economics",
  "EDPR": "Educational Practice",
  "EDUC": "Education",
  "EEB": "Evolution, Ecology, & Behavior",
  "EIL": "English as an Intl Language",
  "ENG": "Engineering",
  "ENGL": "English",
  "ENSU": "Environmental Sustainability",
  "ENT": "Entomology",
  "ENVS": "Environmental Studies",
  "EPOL": "Ed Policy, Org & Ldership",
  "EPSY": "Educational Psychology",
  "ERAM": "Education Research and Methods",
  "ES": "Energy Systems",
  "ESE": "Earth, Society, & Environment",
  "ESL": "English as a Second Language",
  "ETMA": "ETMA- Engineering Technology & Management for Agricultural Systems",
  "EURO": "European Union Studies",
  "EXP": "Exploratory Studies",
  "FAA": "Fine and Applied Arts",
  "FIN": "Finance",
  "FLTE": "Foreign Language Teacher Education",
  "FR": "French",
  "FSHN": "Food Science & Human Nutrition",
  "GC": "Graduate College",
  "GEOL": "Geology",
  "GER": "German",
  "GGIS": "Geography & Geographic Information Science",
  "GLBL": "Global Studies",
  "GMC": "Germanic",
  "GRK": "Greek",
  "GRKM": "Modern Greek",
  "GSD": "Game Studies and Design",
  "GWS": "Gender and Women's Studies",
  "HBSE": "Healthcare, Biomedical Science and Engineering",
  "HDFS": "Human Dev and Family Studies",
  "HEBR": "Hebrew, Modern and Classical",
  "HIST": "History",
  "HK": "Health and Kinesiology",
  "HNDI": "Hindi",
  "HORT": "Horticulture",
  "HT": "Health Technology",
  "HUM": "Humanities Courses",
  "IB": "Integrative Biology",
  "IE": "Industrial Engineering",
  "INFO": "Informatics",
  "IS": "Information Sciences",
  "ITAL": "Italian",
  "JAPN": "Japanese",
  "JOUR": "Journalism",
  "JS": "Jewish Studies",
  "KOR": "Korean",
  "LA": "Landscape Architecture",
  "LAS": "Liberal Arts and Sciences",
  "LAST": "Latin American & Caribbean St",
  "LAT": "Latin",
  "LAW": "Law",
  "LCTL": "Less Commonly Taught Languages",
  "LEAD": "Organizational & Community Leadership",
  "LER": "Labor and Employment Relations",
  "LING": "Linguistics",
  "LLS": "Latina/Latino Studies",
  "MACS": "Media and Cinema Studies",
  "MATH": "Mathematics",
  "MBA": "MBA Program",
  "MCB": "Molecular and Cell Biology",
  "MDIA": "Media",
  "MDVL": "Medieval Studies",
  "ME": "Mechanical Engineering",
  "MICR": "Microbiology",
  "MILS": "Military Science",
  "MIP": "Moleculr & Integrative Physiology",
  "MSE": "Materials Science & Engineering",
  "MUS": "Music",
  "MUSC": "Music Lessons and Ensembles",
  "MUSE": "Museum Studies",
  "NE": "Neural Engineering",
  "NEUR": "Neuroscience",
  "NPRE": "Nuclear, Plasma, Radiological Engineering",
  "NRES": "Natural Resources & Environ Sc",
  "NS": "Naval Science",
  "NUTR": "Nutritional Sciences",
  "PATH": "Pathobiology",
  "PBIO": "Plant Biology",
  "PERS": "Persian",
  "PHIL": "Philosophy",
  "PHYS": "Physics",
  "PLPA": "Plant Pathology",
  "POL": "Polish",
  "PORT": "Portuguese",
  "PS": "Political Science",
  "PSM": "Professional Science Master",
  "PSYC": "Psychology",
  "QUEC": "Quechua",
  "REES": "Russian, East European and Eurasian Studies",
  "REL": "Religion",
  "RHET": "Rhetoric and Composition",
  "RMLG": "Romance Linguistics",
  "RST": "Recreation, Sport, and Tourism",
  "RUSS": "Russian",
  "SAME": "South Asian & Middle Eastern",
  "SBC": "Strategic Brand Communication",
  "SCAN": "Scandinavian",
  "SE": "Systems Engineering and Design",
  "SHS": "Speech and Hearing Science",
  "SLAV": "Slavic",
  "SLCL": "Literatures Cultures Linguistics",
  "SNSK": "Sanskrit",
  "SOC": "Sociology",
  "SOCW": "Social Work",
  "SPAN": "Spanish",
  "SPED": "Special Education",
  "STAT": "Statistics",
  "SWAH": "Swahili",
  "TAM": "Theoretical and Applied Mechanics",
  "TE": "Technology Entrepreneurship",
  "THEA": "Theatre",
  "TMGT": "Technology and Management",
  "TRST": "Translation Studies",
  "TURK": "Turkish",
  "UKR": "Ukrainian",
  "UP": "Urban and Regional Planning",
  "VCM": "Veterinary Clinical Medicine",
  "VM": "Veterinary Medicine Courses",
  "WLOF": "Wolof",
  "WRIT": "Writing Studies",
  "YDSH": "Yiddish",
};

/** "Accountancy" for ACCY, or the prefix itself when the catalog names none. */
export function subjectName(prefix: string): string {
  return ILLINOIS_SUBJECT_NAMES[prefix.toUpperCase()] ?? prefix;
}

/**
 * Whether a search names this department.
 *
 * A plain substring first. Then the root of the word, because the student
 * types "accounting" and the catalog says "Accountancy", "computing" against
 * "Computer Science", "biology" against "Integrative Biology". A word of five
 * letters or more is matched on all but its last three, which is the part the
 * two forms share, and only as the start of a word in the name so that "art"
 * does not light up "Architecture". Short queries stay exact.
 */
export function subjectMatches(prefix: string, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return false;
  const name = subjectName(prefix).toLowerCase();
  if (name.includes(q)) return true;
  const words = q.split(/\s+/).filter(Boolean);
  if (words.length !== 1 || words[0].length < 5) return false;
  const stem = words[0].slice(0, Math.max(5, words[0].length - 3));
  return name.split(/[^a-z]+/).some((w) => w.startsWith(stem));
}
