import type {
  Course,
  OptionDefinition,
  PlanState,
  ProgramDefinition,
  StudentProfile,
} from './types';

const both = ['Fall', 'Spring'] as const;

const cognitiveScienceProgram: ProgramDefinition = {
  id: 'cognitive-science-ab-demo',
  name: 'Cognitive Science',
  degree: 'A.B.',
  totalCredits: 120,
  dataStatus: 'reviewed-demo',
  requirements: [
    {
      id: 'core',
      label: 'University core',
      targetCredits: 42,
      description: 'General education and university-wide requirements.',
    },
    {
      id: 'foundations',
      label: 'Major foundations',
      targetCredits: 12,
      description: 'Introductory work across cognitive science disciplines.',
    },
    {
      id: 'computation',
      label: 'Computation',
      targetCredits: 18,
      description: 'Programming, algorithms, and artificial intelligence.',
    },
    {
      id: 'mind',
      label: 'Mind & brain',
      targetCredits: 12,
      description: 'Psychology, cognition, and neuroscience.',
    },
    {
      id: 'language-philosophy',
      label: 'Language & philosophy',
      targetCredits: 15,
      description: 'Language, logic, mind, and meaning.',
    },
    {
      id: 'methods',
      label: 'Research methods',
      targetCredits: 7,
      description: 'Statistics and empirical research design.',
    },
  ],
};

const computerScienceProgram: ProgramDefinition = {
  id: 'computer-science-bs-placeholder',
  name: 'Computer Science',
  degree: 'B.S.',
  totalCredits: 120,
  dataStatus: 'placeholder',
  requirements: [
    {
      id: 'core',
      label: 'University core',
      targetCredits: 42,
      description: 'General education and university-wide requirements.',
    },
    {
      id: 'foundations',
      label: 'Math & science',
      targetCredits: 24,
      description: 'Calculus, statistics, and laboratory science.',
    },
    {
      id: 'computation',
      label: 'Computer science major',
      targetCredits: 42,
      description:
        'Programming, systems, theory, and upper-division electives.',
    },
    {
      id: 'methods',
      label: 'Quantitative methods',
      targetCredits: 6,
      description: 'Statistical and empirical methods.',
    },
  ],
};

const psychologyProgram: ProgramDefinition = {
  id: 'psychology-bs-placeholder',
  name: 'Psychology',
  degree: 'B.S.',
  totalCredits: 120,
  dataStatus: 'placeholder',
  requirements: [
    {
      id: 'core',
      label: 'University core',
      targetCredits: 42,
      description: 'General education and university-wide requirements.',
    },
    {
      id: 'foundations',
      label: 'Psychology foundation',
      targetCredits: 15,
      description: 'Introductory psychology and supporting science.',
    },
    {
      id: 'mind',
      label: 'Psychology major',
      targetCredits: 30,
      description: 'Upper-division psychology breadth and depth.',
    },
    {
      id: 'methods',
      label: 'Statistics & research',
      targetCredits: 10,
      description: 'Research design, statistics, and analysis.',
    },
  ],
};

export const samplePrograms = [
  cognitiveScienceProgram,
  computerScienceProgram,
  psychologyProgram,
];

export const sampleProgram = cognitiveScienceProgram;

export const secondaryMajorOptions: OptionDefinition[] = [
  { id: 'none', label: 'No second major', status: 'none' },
  {
    id: 'computer-science-bs-placeholder',
    label: 'Computer Science, B.S.',
    status: 'placeholder',
  },
  {
    id: 'psychology-bs-placeholder',
    label: 'Psychology, B.S.',
    status: 'placeholder',
  },
  {
    id: 'data-science-bs-placeholder',
    label: 'Data Science, B.S.',
    status: 'placeholder',
  },
];

export const minorOptions: OptionDefinition[] = [
  { id: 'none', label: 'No minor', status: 'none' },
  {
    id: 'ai-minor-placeholder',
    label: 'Artificial Intelligence',
    status: 'placeholder',
  },
  { id: 'ling-minor-placeholder', label: 'Linguistics', status: 'placeholder' },
  { id: 'stat-minor-placeholder', label: 'Statistics', status: 'placeholder' },
];

export const certificateOptions: OptionDefinition[] = [
  { id: 'none', label: 'No certificate', status: 'none' },
  {
    id: 'applied-data-placeholder',
    label: 'Applied Data Science',
    status: 'placeholder',
  },
  { id: 'new-media-placeholder', label: 'New Media', status: 'placeholder' },
  {
    id: 'sustainability-placeholder',
    label: 'Sustainability',
    status: 'placeholder',
  },
];

export const graduationOptions = [
  'Spring 2029',
  'Spring 2030',
  'Spring 2031',
  'Spring 2032',
];

export const sampleStudentProfile: StudentProfile = {
  primaryMajorId: cognitiveScienceProgram.id,
  secondaryMajorId: 'none',
  minorId: 'ai-minor-placeholder',
  certificateId: 'none',
  graduationLabel: 'Spring 2030',
  careerInterests: 'Human-centered AI, language technology',
  scholarshipPlan: 'hope',
  minimumTermCredits: 12,
  targetGpa: 3,
  preferredFormat: 'Any',
  preferredTime: 'Any',
};

export const sampleCourses: Course[] = [
  {
    id: 'fyos-1001',
    code: 'FYOS 1001',
    title: 'First-Year Odyssey',
    credits: 1,
    description:
      'A small seminar introducing first-year students to faculty research and university life.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['first year', 'seminar'],
  },
  {
    id: 'csci-1301',
    code: 'CSCI 1301',
    title: 'Computing & Programming',
    credits: 4,
    description:
      'An introduction to problem solving, programming, and core computing concepts.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['programming', 'foundational'],
    mapPosition: { x: 18, y: 63 },
    pathwayRole: 'required',
  },
  {
    id: 'math-2250',
    code: 'MATH 2250',
    title: 'Calculus I',
    credits: 4,
    description:
      'Limits, derivatives, integrals, and applications for science and technology.',
    cluster: 'Foundations',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['math', 'quantitative'],
  },
  {
    id: 'engl-1101',
    code: 'ENGL 1101',
    title: 'English Composition I',
    credits: 3,
    description:
      'Academic writing, rhetorical awareness, and evidence-based argument.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['writing', 'core'],
  },
  {
    id: 'comm-1110',
    code: 'COMM 1110',
    title: 'Public Speaking',
    credits: 3,
    description: 'Theory and practice of clear public communication.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['communication', 'core'],
  },
  {
    id: 'csci-1302',
    code: 'CSCI 1302',
    title: 'Software Development',
    credits: 4,
    description:
      'Object-oriented software development, testing, modularity, and data structures.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-1301'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['programming', 'software'],
    mapPosition: { x: 29, y: 72 },
  },
  {
    id: 'psyc-1101',
    code: 'PSYC 1101',
    title: 'Elementary Psychology',
    credits: 3,
    description:
      'Foundational principles spanning learning, perception, motivation, and behavior.',
    cluster: 'Mind & Brain',
    requirementIds: ['foundations'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['psychology', 'foundational'],
    mapPosition: { x: 58, y: 23 },
    pathwayRole: 'required',
  },
  {
    id: 'ling-2100',
    code: 'LING 2100',
    title: 'The Study of Language',
    credits: 3,
    description:
      'The scientific study of language, grammar, variation, and change.',
    cluster: 'Language',
    requirementIds: ['foundations'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['language', 'foundational'],
    mapPosition: { x: 69, y: 64 },
    pathwayRole: 'required',
  },
  {
    id: 'engl-1102',
    code: 'ENGL 1102',
    title: 'English Composition II',
    credits: 3,
    description: 'Research-based writing and sustained academic inquiry.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: ['engl-1101'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['writing', 'core'],
  },
  {
    id: 'arts-2000',
    code: 'ARTS 2000',
    title: 'Art Appreciation',
    credits: 3,
    description: 'Visual analysis and the role of art in culture.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'Online',
    tags: ['arts', 'online'],
    section: {
      termId: '2027-spring',
      status: 'waitlist',
      seatsRemaining: 0,
      meeting: 'Asynchronous',
      location: 'Online',
      capturedAt: 'Demo snapshot',
    },
  },
  {
    id: 'csci-2610',
    code: 'CSCI 2610',
    title: 'Discrete Mathematics for CS',
    credits: 3,
    description:
      'Logic, proof, combinatorics, probability, and discrete structures for computer science.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-1301'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['logic', 'math'],
    mapPosition: { x: 22, y: 48 },
  },
  {
    id: 'phil-2500',
    code: 'PHIL 2500',
    title: 'Symbolic Logic',
    credits: 3,
    description:
      'Contemporary methods for distinguishing correct from incorrect deductive arguments.',
    cluster: 'Philosophy',
    requirementIds: ['language-philosophy'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['logic', 'reasoning'],
    mapPosition: { x: 47, y: 52 },
  },
  {
    id: 'stat-2000',
    code: 'STAT 2000',
    title: 'Introductory Statistics',
    credits: 4,
    description:
      'Data collection, probability, inference, regression, and hypothesis testing.',
    cluster: 'Foundations',
    requirementIds: ['methods'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['statistics', 'data'],
    mapPosition: { x: 36, y: 24 },
    pathwayRole: 'required',
  },
  {
    id: 'biol-1103',
    code: 'BIOL 1103',
    title: 'Concepts in Biology',
    credits: 4,
    description: 'Core biological principles with laboratory experience.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['science', 'lab'],
  },
  {
    id: 'csci-2720',
    code: 'CSCI 2720',
    title: 'Data Structures',
    credits: 4,
    description:
      'Design, analysis, and implementation of fundamental data structures and algorithms.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-1302'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['algorithms', 'programming'],
    mapPosition: { x: 13, y: 79 },
  },
  {
    id: 'psyc-3990',
    code: 'PSYC 3990',
    title: 'Research Analysis in Psychology',
    credits: 3,
    description:
      'Quantitative methods for psychological research and direct experience with data analysis.',
    cluster: 'Mind & Brain',
    requirementIds: ['methods'],
    prerequisites: ['psyc-1101'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['research', 'statistics'],
    mapPosition: { x: 47, y: 32 },
  },
  {
    id: 'ling-3150',
    code: 'LING 3150',
    title: 'Generative Syntax',
    credits: 3,
    description:
      'Formal techniques for analyzing syntactic patterns across languages.',
    cluster: 'Language',
    requirementIds: ['language-philosophy'],
    prerequisites: ['ling-2100'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['syntax', 'formal systems'],
    section: {
      termId: '2028-spring',
      status: 'open',
      seatsRemaining: 8,
      meeting: 'MWF 11:30-12:20',
      location: 'Gilbert Hall',
      travelNote:
        'The preceding sample section ends at the SLC 15 minutes earlier.',
      capturedAt: 'Demo snapshot',
    },
    mapPosition: { x: 76, y: 74 },
  },
  {
    id: 'hist-2111',
    code: 'HIST 2111',
    title: 'American History to 1865',
    credits: 3,
    description:
      'American political, social, and cultural history through the Civil War.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'Online',
    tags: ['history', 'core'],
  },
  {
    id: 'astr-1010',
    code: 'ASTR 1010',
    title: 'Astronomy of the Solar System',
    credits: 3,
    description:
      'A survey of the solar system and the methods of observational astronomy.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['science', 'space'],
  },
  {
    id: 'csci-3030',
    code: 'CSCI 3030',
    title: 'Computing, Ethics & Society',
    credits: 3,
    description:
      'Social and ethical issues in computer science and information technology.',
    cluster: 'Philosophy',
    requirementIds: ['language-philosophy'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['ethics', 'technology'],
    mapPosition: { x: 42, y: 70 },
  },
  {
    id: 'psyc-4100',
    code: 'PSYC 4100',
    title: 'Cognitive Psychology',
    credits: 3,
    description:
      'Experimental and theoretical approaches to memory, attention, language, and thought.',
    cluster: 'Mind & Brain',
    requirementIds: ['mind'],
    prerequisites: ['psyc-1101'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['cognition', 'memory'],
    mapPosition: { x: 64, y: 34 },
  },
  {
    id: 'span-2001',
    code: 'SPAN 2001',
    title: 'Intermediate Spanish I',
    credits: 3,
    description:
      'Intermediate language study emphasizing communication and cultural knowledge.',
    cluster: 'Language',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['language', 'culture'],
  },
  {
    id: 'csci-3360',
    code: 'CSCI 3360',
    title: 'Data Science & Applied ML I',
    credits: 3,
    description:
      'Data science workflows and introductory machine learning methods.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-2720', 'stat-2000'],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['machine learning', 'data'],
    mapPosition: { x: 26, y: 36 },
  },
  {
    id: 'phil-2030',
    code: 'PHIL 2030',
    title: 'Introduction to Ethics',
    credits: 3,
    description:
      'Major approaches to ethical reasoning and contemporary moral questions.',
    cluster: 'Philosophy',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'Online',
    tags: ['ethics', 'core'],
  },
  {
    id: 'arti-3550',
    code: 'ARTI 3550',
    title: 'Introduction to Cognitive Science',
    credits: 3,
    description:
      'An interdisciplinary introduction to minds, intelligence, and cognition.',
    cluster: 'Foundations',
    requirementIds: ['foundations'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'In person',
    tags: ['cognitive science', 'interdisciplinary'],
    mapPosition: { x: 49, y: 43 },
    pathwayRole: 'required',
  },
  {
    id: 'psyc-4140',
    code: 'PSYC 4140',
    title: 'Cognitive Neuroscience',
    credits: 3,
    description:
      'Neural systems underlying attention, memory, language, and decision making.',
    cluster: 'Mind & Brain',
    requirementIds: ['mind'],
    prerequisites: ['psyc-4100'],
    offeredIn: ['Spring'],
    format: 'In person',
    tags: ['neuroscience', 'cognition'],
    mapPosition: { x: 74, y: 20 },
  },
  {
    id: 'csci-4550',
    code: 'CSCI 4550',
    title: 'Artificial Intelligence',
    credits: 3,
    description:
      'Core ideas and methods for representing and building intelligent systems.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-2720'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['AI', 'search'],
    mapPosition: { x: 17, y: 27 },
    pathwayRole: 'choice',
  },
  {
    id: 'span-2002',
    code: 'SPAN 2002',
    title: 'Intermediate Spanish II',
    credits: 3,
    description: 'Continued intermediate language study and cultural analysis.',
    cluster: 'Language',
    requirementIds: ['core'],
    prerequisites: ['span-2001'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['language', 'culture'],
  },
  {
    id: 'soci-1101',
    code: 'SOCI 1101',
    title: 'Introductory Sociology',
    credits: 3,
    description:
      'Social institutions, inequality, culture, and group behavior.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'Online',
    tags: ['society', 'core'],
  },
  {
    id: 'arti-4555',
    code: 'ARTI 4555',
    title: 'Foundations of Machine Learning',
    credits: 3,
    description:
      'Mathematical and computational foundations of modern machine learning.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-2720', 'stat-2000'],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['machine learning', 'AI'],
    mapPosition: { x: 10, y: 42 },
    pathwayRole: 'choice',
  },
  {
    id: 'phil-4310',
    code: 'PHIL 4310',
    title: 'Philosophy of Mind',
    credits: 3,
    description:
      'The nature of consciousness, thought, perception, and mental representation.',
    cluster: 'Philosophy',
    requirementIds: ['language-philosophy'],
    prerequisites: [],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['mind', 'consciousness'],
    mapPosition: { x: 57, y: 61 },
  },
  {
    id: 'ling-4160',
    code: 'LING 4160',
    title: 'Compositional Semantics',
    credits: 3,
    description:
      'Formal approaches to how linguistic expressions combine to create meaning.',
    cluster: 'Language',
    requirementIds: ['language-philosophy'],
    prerequisites: ['ling-3150'],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['semantics', 'logic'],
    mapPosition: { x: 85, y: 57 },
  },
  {
    id: 'engl-3370',
    code: 'ENGL 3370',
    title: 'Literature & Artificial Intelligence',
    credits: 3,
    description:
      'Literary approaches to artificial intelligence and human-machine relations.',
    cluster: 'Language',
    requirementIds: ['core'],
    prerequisites: ['engl-1102'],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['AI', 'literature'],
  },
  {
    id: 'geog-4591',
    code: 'GEOG 4591',
    title: 'Geospatial Artificial Intelligence',
    credits: 3,
    description:
      'Artificial intelligence methods for geographic and spatial data.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['stat-2000'],
    offeredIn: ['Fall'],
    format: 'Hybrid',
    tags: ['AI', 'geography'],
  },
  {
    id: 'arti-4950',
    code: 'ARTI 4950',
    title: 'Directed Readings in Cognitive Science',
    credits: 3,
    description:
      'Faculty-guided advanced reading in a focused area of cognitive science.',
    cluster: 'Foundations',
    requirementIds: ['mind'],
    prerequisites: ['arti-3550'],
    offeredIn: [...both],
    format: 'In person',
    tags: ['research', 'capstone'],
  },
  {
    id: 'csci-4050',
    code: 'CSCI 4050',
    title: 'Software Engineering',
    credits: 3,
    description:
      'Team-based software design, development process, testing, and maintenance.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: ['csci-2720'],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['software', 'teamwork'],
  },
  {
    id: 'ling-4570',
    code: 'LING 4570',
    title: 'Natural Language Processing',
    credits: 3,
    description:
      'Computational techniques for analyzing and generating human language.',
    cluster: 'Language',
    requirementIds: ['language-philosophy'],
    prerequisites: ['ling-2100', 'csci-1301'],
    offeredIn: ['Spring'],
    format: 'In person',
    tags: ['NLP', 'AI'],
    mapPosition: { x: 87, y: 78 },
  },
  {
    id: 'cmlt-3080',
    code: 'CMLT 3080',
    title: 'Playing with Robots',
    credits: 3,
    description:
      'Literary representations of automata and intelligent machines.',
    cluster: 'Language',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: ['Spring'],
    format: 'In person',
    tags: ['robots', 'literature'],
  },
  {
    id: 'musi-2020',
    code: 'MUSI 2020',
    title: 'Introduction to World Music',
    credits: 3,
    description: 'Music as culture across a range of global traditions.',
    cluster: 'University Core',
    requirementIds: ['core'],
    prerequisites: [],
    offeredIn: [...both],
    format: 'Online',
    tags: ['music', 'culture'],
  },
  {
    id: 'ling-4105',
    code: 'LING 4105',
    title: 'Psycholinguistics',
    credits: 3,
    description: 'How people understand, produce, and acquire language.',
    cluster: 'Language',
    requirementIds: ['language-philosophy'],
    prerequisites: ['ling-2100'],
    offeredIn: ['Fall'],
    format: 'In person',
    tags: ['language', 'cognition'],
  },
  {
    id: 'juri-5581',
    code: 'JURI 5581',
    title: 'Law & Artificial Intelligence',
    credits: 3,
    description:
      'Legal questions raised by automated decision making and AI systems.',
    cluster: 'Philosophy',
    requirementIds: ['language-philosophy'],
    prerequisites: [],
    offeredIn: ['Spring'],
    format: 'In person',
    tags: ['AI', 'law'],
    mapPosition: { x: 57, y: 82 },
  },
  {
    id: 'mist-5450',
    code: 'MIST 5450',
    title: 'Generative Artificial Intelligence',
    credits: 3,
    description:
      'Business applications, workflows, and implications of generative AI.',
    cluster: 'Computation',
    requirementIds: ['computation'],
    prerequisites: [],
    offeredIn: ['Spring'],
    format: 'Hybrid',
    tags: ['generative AI', 'business'],
    mapPosition: { x: 32, y: 87 },
  },
];

const seedTerms: PlanState['terms'] = [
  {
    id: '2026-fall',
    label: 'Fall 2026',
    year: 1,
    season: 'Fall',
    courseIds: [
      'fyos-1001',
      'csci-1301',
      'math-2250',
      'engl-1101',
      'comm-1110',
    ],
  },
  {
    id: '2027-spring',
    label: 'Spring 2027',
    year: 1,
    season: 'Spring',
    courseIds: [
      'csci-1302',
      'psyc-1101',
      'ling-2100',
      'engl-1102',
      'arts-2000',
    ],
  },
  {
    id: '2027-fall',
    label: 'Fall 2027',
    year: 2,
    season: 'Fall',
    courseIds: ['csci-2610', 'phil-2500', 'stat-2000', 'biol-1103'],
  },
  {
    id: '2028-spring',
    label: 'Spring 2028',
    year: 2,
    season: 'Spring',
    courseIds: [
      'csci-2720',
      'psyc-3990',
      'ling-3150',
      'hist-2111',
      'astr-1010',
    ],
  },
  {
    id: '2028-fall',
    label: 'Fall 2028',
    year: 3,
    season: 'Fall',
    courseIds: [
      'csci-3030',
      'psyc-4100',
      'span-2001',
      'csci-3360',
      'phil-2030',
    ],
  },
  {
    id: '2029-spring',
    label: 'Spring 2029',
    year: 3,
    season: 'Spring',
    courseIds: [
      'arti-3550',
      'psyc-4140',
      'csci-4550',
      'span-2002',
      'soci-1101',
    ],
  },
  {
    id: '2029-fall',
    label: 'Fall 2029',
    year: 4,
    season: 'Fall',
    courseIds: [
      'arti-4555',
      'phil-4310',
      'ling-4160',
      'engl-3370',
      'geog-4591',
    ],
  },
  {
    id: '2030-spring',
    label: 'Spring 2030',
    year: 4,
    season: 'Spring',
    courseIds: [
      'arti-4950',
      'csci-4050',
      'ling-4570',
      'cmlt-3080',
      'musi-2020',
    ],
  },
];

export function createSamplePlan(): PlanState {
  return {
    schemaVersion: 1,
    programId: sampleProgram.id,
    graduationLabel: 'Spring 2030',
    completedCourseIds: [],
    terms: seedTerms.map((term) => ({
      ...term,
      courseIds: [...term.courseIds],
    })),
  };
}

export function createSampleProfile(): StudentProfile {
  return { ...sampleStudentProfile };
}

export function relabelPlanForGraduation(
  plan: PlanState,
  graduationLabel: string,
): PlanState {
  const graduationYear = Number(graduationLabel.match(/\d{4}/)?.[0]);
  if (!Number.isFinite(graduationYear)) {
    return { ...plan, graduationLabel };
  }

  return {
    ...plan,
    graduationLabel,
    terms: plan.terms.map((term) => {
      const calendarYear =
        term.season === 'Fall'
          ? graduationYear - (5 - term.year)
          : graduationYear - (4 - term.year);
      return { ...term, label: `${term.season} ${calendarYear}` };
    }),
  };
}
